spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app?serverTimezone=UTC
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 288100
      maximum-pool-size: 42


